### PR TITLE
Add Fairwinds Insights

### PR DESCRIPTION
**Pull request by rbren**
Let me know if there's anything else you need!

### CODE REVIEW

**Comment by anderseknert** [comment]
Thanks @rbren ! 

I don't mind commercial projects here, but unless there is an easy way try this out it's a bit hard to tell whether this is an awesome project? :) 

The website looks real nice though!

**Comment by rbren** [comment]
Hmm, a few other possibilities:
* we could link to https://insights.fairwinds.com, which includes a free trial
* we could link to https://insights.fairwinds.com/orgs/centaurus/clusters, which is a demo environment
* we could link to https://insights.fairwinds.com/orgs/centaurus/policy/new, which shows off the OPA integration in the demo environment

Which do you think would be best?

**Comment by anderseknert** [comment]
I think the front page link is fine. I signed up for a demo and tried it out in a local kind cluster. Looks pretty nice! Being able to group violations and add severity rating was a nice touch. I'll merge this as it is but I'm probably going to create a separate "Commercial" section in the bottom later where I'll move this along with some other projects if you think that's OK?

**Comment by rbren** [comment]
👍 sounds good to me. Thanks Anders!

**Pull request merged**
